Repository makchamakers/makchata, pull requests merged in 2023-11, with the labels that each got.

#48 [common] icon, image 정리
  README.md
  image-1.png
  image.png
  public/Directions bus.png
  public/Directions subway.png
  public/Location_on.png
  public/assets/icons/01Search_01Default.png
  public/assets/icons/02Route_01한눈에보기페이지_01바텀시트Up.png
  public/assets/icons/02Route_01한눈에보기페이지_01바텀시트Up_01Modal.png
  public/assets/icons/03Setting_01인덱스.png
  public/assets/icons/03Setting_02알람주기관리.png
  public/assets/icons/03Setting_03즐겨찾기관리_01디폴트_02인풋입력.png
  public/assets/icons/04Completed_01디폴트.png
  public/assets/icons/04Completed_02도착했어요.png
  public/assets/icons/ic_bus_white.svg
  public/assets/icons/ic_char_crying.svg
  public/assets/icons/ic_char_default.svg
  public/assets/icons/ic_exclamationMark_gray.svg
  public/assets/icons/ic_location_gray.svg
  public/assets/icons/ic_sub_white.svg
  public/assets/images/img_mainPage_off.png
  public/assets/images/img_mainPage_on.jpg
  public/assets/images/img_routePage_summary.png
  public/assets/images/img_searchPage_result.png
  public/assets/images/img_thumbnail.png
  public/crying.png
  public/detailroute.svg
  public/exclamation_mark.png
  public/makchata_illust.png
  public/og-image.png
  public/vercel.svg
  src/app/android-icon-192x192.png
  src/app/apple-icon-114x114.png
  src/app/apple-icon-120x120.png
  src/app/apple-icon-144x144.png
  src/app/apple-icon-152x152.png
  src/app/apple-icon-180x180.png
  src/app/apple-icon-72x72.png
  src/app/apple-icon-76x76.png
  src/app/apple-icon1.png
  src/app/apple-icon2.png
  src/app/favicon-16x16.png
  src/app/favicon-32x32.png
  src/app/favicon-96x96.png
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
Labels: 🔡 style

#49 [common] husky와 lint-staged 추가, gitignore 수정
  .gitignore
  .husky/_/husky.sh
  .husky/pre-commit
  package-lock.json
  package.json
  yarn.lock
Labels: 🧹 chore, ❓question

#54 [chore] lint-staged 에러사항 수정
  .husky/pre-commit
  package.json
  src/app/page.tsx
  src/components/route/AlarmModal.tsx
  src/recoil/alarm.ts
  yarn.lock
Labels: 🧹 chore

#57 [common] pr template 추가
  .github/workflows/PULL_REQUEST_TEMPLATE.md
Labels: 📝 docs

#58 [common] error, warning 해결
  .eslintrc.json
  next.config.js
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/search/page.tsx
Labels: 🐛bug

#60 [common] pr template 위치 변경
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 docs

#61 [common] warning 해결로 인한 og카드 미작동, 코드 복구 (#55)
  src/app/layout.tsx
Labels: 🐛bug

#67 feat : 출발지 입력했을시 출발지, 목적지에 대한 검색 결과 나열 (#66)
  src/api/api.ts
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/search/Input.tsx
  src/components/search/Input/ArrivalInput.tsx
  src/components/search/Input/DepartureInput.tsx
  src/components/search/PlaceCard.tsx
  src/hooks/useDebounce.ts
  src/recoil/search.ts
Labels: 🚀 feat, 🙏sorry

#70 [search] input, atom refactor
  src/api/api.ts
  src/app/search/page.tsx
  src/components/search/Input.tsx
  src/components/search/Input/ArrivalInput.tsx
  src/components/search/Input/DepartureInput.tsx
  src/components/search/PlaceCard.tsx
  src/hooks/useDebounce.ts
  src/recoil/search.ts
  src/type/search.ts
Labels: ♻️ refactor

#71 [route] 지도에 경로 폴리라인 그리기 구현
  src/api/api.ts
  src/app/route/[index]/page.tsx
  src/components/route/Summary.tsx
  src/components/route/summary/Map.tsx
  src/recoil/state.ts
  src/type/path.ts
  src/type/route.ts
Labels: 🚀 feat, 🙏sorry

#77 [common] api 관련 함수들, src/api 에서 src/utils/apis 로 이동
  src/components/route/summary/Map.tsx
  src/utils/apis/path.ts
  src/utils/search/getPathDetail.ts
Labels: 🐛bug

#79 [main]경로 상세 퍼블리싱
  src/app/page.tsx
  src/components/main/DetailRoute.tsx
  src/constants/routeColor.ts
Labels: ⚒️ fix

#80 [search] : 결과 route bar 넣기 레이아웃 (#76)
  public/assets/icons/ic_current_location.png
  public/assets/icons/ic_exchange.png
  public/assets/icons/ic_home.svg
  public/assets/icons/ic_location.svg
  public/assets/icons/ic_school.svg
  public/assets/icons/ic_setting.svg
  public/assets/icons/ic_work.svg
  public/assets/icons/ic_x_lg.svg
  public/assets/icons/ic_x_sm.png
  src/api/api.ts
  src/app/search/page.tsx
  src/components/search/Button/ChipButton.tsx
  src/components/search/Button/CurrentLocationButton.tsx
  src/components/search/Input.tsx
  src/components/search/PlaceCard.tsx
  src/components/search/ResultCard.tsx
  src/components/search/ResultCards.tsx
  src/components/search/RouteCard.tsx
  src/components/search/assets/LocationIcon.tsx
  src/components/search/assets/MyHome.tsx
  src/components/search/assets/Setting.tsx
  src/components/search/assets/Switch.tsx
  src/components/search/assets/X.tsx
  src/components/search/assets/index.ts
  src/components/search/index.ts
  src/recoil/search.ts
  src/type/search.ts
  src/utils/time/boardingTime.ts
  yarn.lock
Labels: 🚀 feat
