Repository makchamakers/makchata, pull requests merged in 2023-12, with the labels that each got.

#88 [search] placeCard에 touchStart, End 이벤트
  public/assets/icons/ic_home_gray.svg
  public/assets/icons/ic_setting_gray.svg
  public/assets/icons/ic_user.svg
  src/app/search/page.tsx
  src/components/HomeIcon.tsx
  src/components/NavigationBar.tsx
  src/components/PersonIcon.tsx
  src/components/SettingIcon.tsx
  src/components/search/Card/PlaceCard.tsx
  src/components/search/Card/ResultCard.tsx
  src/components/search/Card/ResultCards.tsx
  src/components/search/Card/RouteCard.tsx
  src/components/search/RouteCard.tsx
  src/components/search/index.ts
  src/recoil/search.ts
  src/type/search.ts
Labels: 🚀 feat

#97 [route] 지도에 이동경로 페이지 값 연결
  src/components/route/summary/Map.tsx
  src/type/path.ts
  src/type/search.ts
  yarn.lock
Labels: 🚀 feat

#100 [route] 바텀시트 상단 api 연결(막차시간만)
  src/app/route/[index]/page.tsx
  src/components/route/Summary.tsx
  src/components/route/bottomSheet/TopInfo.tsx
  src/components/route/summary/Map.tsx
  src/constants/queryKey.ts
  src/hooks/useGetParamsIndex.ts
  src/hooks/usePathDetailQuery.ts
Labels: 🚀 feat, ⚒️ fix

#104 [search] fix : 병합 문제 해결
  src/app/search/page.tsx
  src/components/search/Card/RouteCard.tsx
  src/recoil/search.ts
  src/type/search.ts
Labels: ⚒️ fix
